import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
function config(){const p=new URLSearchParams(location.search);return{count:Math.max(3,Math.min(20,+p.get('count')||8)),duration:Math.max(5,Math.min(60,+p.get('duration')||14)),weather:p.get('weather')!=='0',place:p.get('place')||'Nieuwveen'}}
function tm(v){const d=new Date(v);return isNaN(d)?'':d.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}
function short(s='',m=210){const t=String(s).replace(/\s+/g,' ').trim();if(t.length<=m)return t;const c=t.slice(0,m);return c.slice(0,Math.max(c.lastIndexOf(' '),m-30)).trim()+'…'}
function App(){const c=config(),[items,setItems]=useState([]),[active,setActive]=useState(0),[now,setNow]=useState(new Date()),[temp,setTemp]=useState(null),[err,setErr]=useState('');
useEffect(()=>{async function load(){try{const r=await fetch('/api/news',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Tennisnieuws niet beschikbaar');setItems(d.items.slice(0,c.count));setErr('')}catch(e){setErr(e.message)}}load();const t=setInterval(load,300000);return()=>clearInterval(t)},[]);
useEffect(()=>{if(!items.length)return;const t=setInterval(()=>setActive(i=>(i+1)%items.length),c.duration*1000);return()=>clearInterval(t)},[items.length]);
useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
useEffect(()=>{if(!c.weather)return;async function w(){try{const g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(c.place)}&count=1&language=nl&format=json&countryCode=NL`).then(r=>r.json()),p=g.results?.[0];if(!p)return;const d=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m&timezone=Europe%2FAmsterdam`).then(r=>r.json());setTemp(Math.round(d.current.temperature_2m))}catch(e){}}w()},[]);
const cur=items[active],up=useMemo(()=>items.length?Array.from({length:Math.min(4,items.length-1)},(_,o)=>items[(active+o+1)%items.length]):[],[items,active]);return <div className="app"><header><div className="brand"><div className="nos">NOS</div><div className="ball">●</div><strong>TENNIS</strong><small>SPORT</small></div><div className="top">{c.weather&&<span>{c.place} {temp==null?'--':temp+'°C'}</span>}<span className={err?'bad':'live'}>{err?'RSS FOUT':'TENNIS LIVE'}</span><div><b>{now.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}</b><small>{now.toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'})}</small></div></div></header><main><section className="hero"><div className="story" key={cur?.link||active}><div className="media">{cur?.image&&<img src={cur.image}/>}</div><div className="shade"/><div className="copy"><small>● LAATSTE TENNISNIEUWS</small><h1>{err&&!cur?'Tennisnieuws tijdelijk niet beschikbaar':cur?.title||'Tennisnieuws laden...'}</h1><p>{short(cur?.description)}</p><time>{tm(cur?.published)}</time>{err&&<div className="error">{err}</div>}</div></div></section><aside><div className="courtline"></div><small>NOS SPORT TENNIS</small><h2>Hierna</h2><div className="list">{up.map((x,i)=><div className="item" key={x.link||i}><b>{String(i+1).padStart(2,'0')}</b><div><strong>{x.title}</strong><small>{tm(x.published)}</small></div></div>)}</div><footer>Feed: NOS Sport Tennis · {active+1}/{items.length}</footer></aside></main></div>}
createRoot(document.getElementById('root')).render(<App/>);