import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const defaults={category:'algemeen',count:8,duration:14,weather:true,place:'Nieuwveen'};
function getCfg(){const p=new URLSearchParams(location.search);return{category:p.get('category')||defaults.category,count:Math.max(3,Math.min(20,+p.get('count')||defaults.count)),duration:Math.max(5,Math.min(60,+p.get('duration')||defaults.duration)),weather:p.get('weather')!=='0',place:p.get('place')||defaults.place}}
function time(v){const d=new Date(v);return isNaN(d)?'':d.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}
function shortText(s='',max=210){const t=String(s).replace(/\s+/g,' ').trim();if(t.length<=max)return t;const c=t.slice(0,max);return c.slice(0,Math.max(c.lastIndexOf(' '),max-30)).trim()+'…'}
function App(){const cfg=getCfg(),[items,setItems]=useState([]),[active,setActive]=useState(0),[now,setNow]=useState(new Date()),[temp,setTemp]=useState(null),[err,setErr]=useState('');
useEffect(()=>{async function load(){try{const r=await fetch(`/api/news?category=${encodeURIComponent(cfg.category)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Nieuws niet beschikbaar');setItems(d.items.slice(0,cfg.count));setErr('')}catch(e){setErr(e.message)}}load();const a=setInterval(load,300000);return()=>clearInterval(a)},[]);
useEffect(()=>{if(!items.length)return;const t=setInterval(()=>setActive(i=>(i+1)%items.length),cfg.duration*1000);return()=>clearInterval(t)},[items.length]);
useEffect(()=>{const c=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(c)},[]);
useEffect(()=>{if(!cfg.weather)return;async function w(){try{const g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(cfg.place)}&count=1&language=nl&format=json&countryCode=NL`).then(r=>r.json()),p=g.results?.[0];if(!p)return;const d=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m&timezone=Europe%2FAmsterdam`).then(r=>r.json());setTemp(Math.round(d.current.temperature_2m))}catch(e){}}w();const t=setInterval(w,600000);return()=>clearInterval(t)},[]);
const cur=items[active],up=useMemo(()=>items.length?Array.from({length:Math.min(4,items.length-1)},(_,o)=>items[(active+o+1)%items.length]):[],[items,active]);return <div className="app"><header><div className="brand"><b>NOS</b><strong>NIEUWS</strong><small>{cfg.category.toUpperCase()}</small></div><div className="top">{cfg.weather&&<span>{cfg.place} {temp==null?'--':temp+'°C'}</span>}<span className={err?'bad':'live'}>{err?'RSS FOUT':'LIVE'}</span><div><b>{now.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}</b><small>{now.toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'})}</small></div></div></header><main><section className="hero"><div className="story" key={cur?.link||active}><div className="media">{cur?.image&&<img src={cur.image}/>}</div><div className="shade"/><div className="copy"><small>LAATSTE NIEUWS</small><h1>{err&&!cur?'Nieuws tijdelijk niet beschikbaar':cur?.title||'Nieuws laden...'}</h1><p>{shortText(cur?.description)}</p><time>{time(cur?.published)}</time>{err&&<div className="error">{err}</div>}</div></div></section><aside><small>NIEUWSUPDATE</small><h2>Hierna</h2><div className="list">{up.map((x,i)=><div className="item" key={x.link||i}><b>{String(i+1).padStart(2,'0')}</b><div><strong>{x.title}</strong><small>{time(x.published)}</small></div></div>)}</div><footer>Bron: NOS RSS · {active+1}/{items.length}</footer></aside></main></div>}
createRoot(document.getElementById('root')).render(<App/>);